 /*Lab06.c * * Created:19/04/2025  * Author: René David González Herrera * Description: Laboratorio 06, programación de microcontroladores. Comunicación serial. *//****************************************/// Encabezado (Libraries)#include <avr/io.h>#include <avr/interrupt.h>uint8_t nonRx=0;uint8_t contador=1;uint8_t mandealb=0;/****************************************/// Function prototypesvoid setup();void initUart();void initadc();void escribirchar(char letra);void escribircadena(char* cadena);/****************************************/// Main Function
int main(void)
{
	setup();
	escribirchar('3');
	escribircadena("Mi cumpleaños es ese dia\n");
	escribircadena("PRIMER IMPRESION");
	while (1)	{		escribircadena("Benvenuti, Porfavor elija una opción:\n");		escribircadena("Para leer el ADC presione 1.\n");		escribircadena("Enviar ascii de caracter al puerto B, 2.\n");		while(nonRx==0);		nonRx=0;		while(mandealb==0);		mandealb=0;			}
}
/****************************************/// NON-Interrupt subroutinesvoid setup(){	cli();	initUart();	DDRB=0xFF;	PORTB=0x00;	initadc();	sei();	}void initadc(){	ADMUX=0;	ADMUX|= (1<<REFS0) | (1<<ADLAR)| (1<<MUX0); //Referencia 5v, Ajustado a la izq, Canal 1	ADCSRA=0;	ADCSRA |= (1<<ADPS2)| (1<< ADPS1)|(1<< ADPS0)|(1<< ADIE)| (1<< ADEN);//Prescalers, interrupcion enable, adc enable.	}void initUart(){	//PInes de comunicación, PD0 y PD1  rx y tx	DDRD |= (1<<DDD1);	DDRD &= ~(1<<DDD0);				// Configuramos el UCSR0A,Todos en 0 para este caso.	UCSR0A=0;	//Configuramos el UCSR0B, Habilitamos interrupciónes al recibir , Habilitamos recepcion y transmisión. 	UCSR0B |= (1<<RXCIE0)| (1<<RXEN0)| (1<<TXEN0);	// Modo asincrono.	UCSR0C =0;	UCSR0C |= (1<< UCSZ01) | (1<< UCSZ00); //Tamaño del caracter	//Nos da 9600 de baudrate con una frecuencia de reloj de 16Mhz	UBRR0= 103;}void escribirchar(char letra){	while((UCSR0A & (1<<UDRE0))==0);//Vemos si el buffer No esta listo para recibir datos y lo hacemos esperar	 UDR0=letra; //Mandamos el caracter}void escribircadena(char* cadena){	for (uint8_t i=0; *(cadena+i) != '\0'; i++)	{		escribirchar(*(cadena+i));	}}/**************************************/// Interrupt routinesISR(USART_RX_vect){	if (contador==1)	{		nonRx=1;		char valor=UDR0;		if (valor ==49)		{			contador=1;			//Leer potenciometro			ADMUX=0;			//Escribir lectura del adc		}		else if (valor==50)		{			contador++;			escribircadena("¿Que ascii desea ver?");					}	}	else if(contador==2)	{		contador=1;		mandealb=1;		//Sacar en el puerto B lo deseado:)		char valor=UDR0;		PORTB=valor;	}		}