;
; Prelab 02.asm
; René David González Herrera.
; Created: 9/02/2025 18:22:34
;
.include "M328PDEF.inc" // Include definitions specific to ATMega328P
.cseg
.org 0x0000

// Configuraci n de la pila?
LDI R16, LOW(RAMEND)
OUT SPL, R16
LDI R16, HIGH(RAMEND)
OUT SPH, R16

//Configuramos el MCU
SETUP:
//CONFIGURAREMOS EL PRESCALER DEL RELOJ DEL SISTEMA
LDI		R16, (1 << CLKPCE)
STS		CLKPR, R16 //HABILITAMOS EL CAMBIO DEL PRESCALER
LDI		R16, 0b00000101 //El FACTOR DE DIVISIÓN DE LOS 16MHz que queremos es 32 
STS		CLKPR, R16 //Frecuencia del reloj =0.5 Mhz


//Iniciamos el Timer0
CALL	INICIAR_TMR0

LDI		R16, 0xff
OUT		DDRC, R16	//PUERTO C COMO SALIDA
LDI		R16, 0X00
OUT		PORTC, R16 //0V EN LOS PINES DEL PUERTO C

LDI		R17, 0X00 //SERA NUESTRO CONTADOR DE 4 BITS

MAIN_LOOP:
	IN		R16, TIFR0		//LEEMOS REGISTRO DE INTERRUPCION DE TIMER 0, OVERFLOW
	SBRS	R16, TOV0		//SALTAR LA SIGUIENTE LINEA SI ESTE BIT ESTA SET, "overflow"
	RJMP	MAIN_LOOP		//SI NO HA HABIDO OVERFLOW REINICIAMOS EL LOOP
	SBI		TIFR0, TOV0		//lIMPIAMOS LA BANDERA DE OVERFLOW
	LDI		R16, 61
	OUT		TCNT0, R16		//VOLVEMOS A CARGAR EL VALOR DESDE DONDE QUEREMOS QUE CUENTE
	CALL	CONTADOR_4BITS
	RJMP	MAIN_LOOP



CONTADOR_4BITS:
	INC		R17
	CALL	ANTIOVERFLOW
	OUT		PORTC, R17
	RET
ANTIOVERFLOW:
	CPI		R17, 0X10
	BREQ	LIMPIAR
	RET
LIMPIAR:
	CLR		R17
	RET


INICIAR_TMR0:
	LDI		R16, (1<<CS02) //PRESCALER QUE QUEREMOS =256= 100
	OUT		TCCR0B, R16 //LE CARGAMOS ESE PRESCALER DE 0 A 256
	LDI		R16, 61 //QUE CUENTE DE 61 A 255
	OUT		TCNT0, R16
	RET
